import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../component/Navbar'
import style from '../styles/Home.module.css'
import Link from 'next/link'
import Main from '../component/Main'
import {HiSparkles} from "react-icons/hi"
export default function Home() {
  return (
    <div className={style.background}>
      <Head>
        <title>Ransom Car Detailing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <div className={style.header}>
          <Navbar/>

          <div className={style.container}>

              <div className={style.service}>
                <Link href=''><p>We Specialize in <span>At Home Services</span></p></Link>
                <h2>Car Detailing Lagos <HiSparkles style={{color:"aqua"}}/></h2>
                <p>High-quality hand wash, affordable prices.<br/> Get washed right where you parked at your office, apartment, or home.
                 </p>
              </div>

                <div className={style.btn}>
                  <Link href='booking'><button className={style.btn1}>Book Now</button></Link>
                  <button>Learn More</button>
                </div>
          
              </div>
          </div>

          <div className={style.main}> 
            <h1>Car Detailing At Home.</h1>
            <p>Get Professional Car Detailing Done Right at Your Home with GoDetail Mobile Detailing. Our<br/> services 
              include complete detailing, washing, waxing, and vacuuming with advanced<br/> protection to keep your car
               looking its best for longer.</p>
          </div>
        <Main/>
    </div>
  )
}
